# **2-D NumPy in Python**

### Objectives

After completing this lab you will be able to:

* Operate comfortably with `NumPy`
* Perform complex operations with `NumPy`

---

### Create a 2- NumPy Array

In [2]:
# Import the libraries

import numpy as np

Consider the list **a** which contains three nested lists **each of equal size**

In [3]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

We can cast the list to a NumPy array as follows:

In [4]:
# Convert the list to a NumPy array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

We can use the attribute `ndim` to obtain the number of axes or dimensions, referred to as the rank

In [5]:
# Show the NumPy array dimensions

A.ndim

2

Attribute `shape` returns a tuple corresponding to the size or number of each dimension

In [6]:
# Show the NumPy array shape

A.shape

(3, 3)

The total number of elements in the array is given by the attribute `size`

In [7]:
# Show the NumPy array size

A.size

9

---

### Accessing Different Elements of a NumPy Array

We can use rectangular brackets to access the different elements of the array. The correspondance between the rectangular brackets, and the list and the rectangular representation is shown in the following figure for a 3x3 array:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500">

We can access the 2nd-row, 3rd column as shown in the following figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">

We simply use the square brackets and the indicies corresponding to the element we would like:

In [8]:
# Access the element on the second row and third column

A[1, 2]

np.int64(23)

We can also use the following notation to obtain the elements:

In [9]:
# Access the element in the second row and the third column

A[1][2]

np.int64(23)

Consider the elements shown in the following figure

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFF.png" width="400">

We can access the elements as follows:

In [10]:
# Access the element inn the first row and first column

A[0][0]

np.int64(11)

We can also use slicing in NumPy arrays. Consider the following figure. We would like to obtain the first two columns in the first row

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400">

This can be done with the following syntax:

In [11]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

Similarly, we can obtain the first two rows of the 3rd column as follows:

In [12]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

Corresponding to the following figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="400"><br />

### Basic Operations

We can also add arrays. The process is identical to matrix addition. Matrix addition of `X` and `Y` is shown in the following figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500">

The NumPy array is given by `X` and `Y`

In [13]:
# Create a NumPy array 'X'

X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [14]:
# Create a NumPy array 'Y'

Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

We can add the NumPy arrays as follows:

In [15]:
# Add 'X' and 'Y'

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplying a NumPy array by a scalar is identical to multiplying a matrix by a scalar. If we multiply the matrix `Y` by the scalar 2, we simply multiply every element in the matrix by 2, as shown in the figure

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500">

We can perform the same operation in NumPy as follows

In [16]:
# Create a NumPy array 'Y'

Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [17]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or *Hadamard Product*. Consider matrix `X` and `Y`. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e., multiplying elements contained in the same color boxes (see below) together. The result is a new matrix that is the same size as matrix `Y` or `X`, as shown in the following figure

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500">

We can perform element-wise product of the array `X` and `Y` as follows:

In [18]:
# Create a NumPy array 'Y'

Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [19]:
# Create a NumPy array 'X'

X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [20]:
# Multiply 'X' with 'Y', assign to 'Z'

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication with the NumPy arrays `A` and `B` as follows:

First, we define matrix `A` and `B`:

In [22]:
# Create a matrix 'A'

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [23]:
# Create a matrix 'B'

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We can use the NumPy function `dot` to multiply the arrays together

In [24]:
# Calculate the dot product of 'A' and 'B'

Z = np.dot(A, B)
Z

array([[0, 2],
       [0, 2]])

In [25]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

We use the NumPy attribute `T` to calculate the transposed matrix

In [26]:
# Create a matrix 'C'

C = np.array([[1, 1], [2, 2], [3, 3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [27]:
# Get the transpose of 'C'

C.T

array([[1, 2, 3],
       [1, 2, 3]])

### Quiz on 2D NumPy Arrays

Consider the following list `a`. Convert it to a NumPy array

In [28]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Calculate the NumPy array size

In [30]:
A.size

12

Access the element on the first row and first and second columns

In [31]:
# Write your code below and press Shift+Enter to execute

A[0][0:2]

array([1, 2])

Perform matrix multiplication with the NumPy arrays `A` and `B`

In [34]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

C = np.dot(A, B)
C

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])